POST http://localhost:3001/api/notes 
Content-Type : application/json

{
    "content": "VS Code Rest Client is cool",
    "important": false
}
###
GET http://localhost:3001/api/notes
###
PUT http://localhost:3001/api/notes/6287f22c9020e922f23ba538
Content-Type: application/json

{
    "content": "test123123",
    "important": true
}
###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "lol",
    "importent": true
}